kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: kubernetes-dashboard
  name: kubernetes-dashboard
  namespace: kubernetes-dashboard
spec:
  ports:
    - nodePort: 30880
			port: 443
      targetPort: 8443
  selector:
    k8s-app: kubernetes-dashboard
	type: NodePort
